// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsthkkljpqzuimkcbcfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzdGhra2xqcHF6dWlta2NiY2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTM4NDcsImV4cCI6MjA3MDA4OTg0N30.S_O1dposQMHReDBORsFYsXgit7OGbsye52f4a9o8gFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});